name: SonarQube Analysis

on:
  workflow_dispatch:


jobs:
  sonarQube:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install SonarScanner CLI
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.7.0.2747-linux/bin:$PATH"
          
      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=src \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload sonar reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: sonar-reports
          path: $HOME/.sonar/cache/
